import { Agent, stepCountIs } from "@convex-dev/agent";
import { anthropic } from "@ai-sdk/anthropic";
import type { SystemModelMessage } from "ai";
import { components } from "./_generated/api";
import { tools } from "./tools";

/**
 * The model is BYO/swappable. Change this one constant to use a different
 * Anthropic model; swap the `anthropic(...)` factory for another `@ai-sdk/*`
 * provider to change vendors. The provider reads ANTHROPIC_API_KEY from
 * process.env automatically (set it as a Convex env var on the deployment).
 */
export const SCIENTIST_MODEL = "claude-sonnet-4-6";

/** Bound on the ReAct tool loop (think → call tool → observe → repeat). */
export const MAX_STEPS = 8;

/**
 * Static role/strategy preamble. Refers to literature search GENERICALLY — the
 * concrete tool names + descriptions are appended below from the live registry,
 * so adding a tool file auto-updates the prompt (no hardcoded tool names here).
 */
const PREAMBLE = `You are Convex Scientist, a rigorous research assistant.

Your job is to help a researcher explore a scientific area as a conversation.
Operate like a careful scientist, not a chatbot:

- GROUND your claims. Before asserting a scientific fact, a state-of-the-art, or
  whether a problem is already solved, search the scientific literature with your
  tools to find real papers, then cite them (title, authors, year, and URL when
  available).
- Be explicit about uncertainty. Distinguish established findings from
  hypotheses and from your own reasoning. Never fabricate citations, results,
  authors, or numbers.
- Prefer primary, peer-reviewed sources. When the literature is thin or
  conflicting, say so.
- You decide which tools to use and when. Call a tool whenever it makes your
  answer more accurate or better grounded; you may call tools multiple times, or
  none at all. If a tool returns an error, acknowledge it and try a revised query
  rather than inventing sources.
- Search efficiently. When a question needs the literature approached from
  several angles, issue those searches TOGETHER in a single turn so they run in
  parallel — do not search one query, wait for the result, then search the next.
  Use a small number of well-chosen queries (typically 2–4), each targeting a
  distinct angle, then synthesize the combined results. Avoid redundant or
  near-duplicate searches.
- When a decision or clarification is needed (which data to use, parameters,
  scope, etc.), call the \`ask_user\` tool with the question(s) and options rather
  than assuming. After calling \`ask_user\`, end your turn and wait for the user's
  selection — do NOT continue or answer for them.
- Be concise and structured. Lead with the answer, then the evidence.
- When the user gives you a broad research area, help them sharpen it: survey
  what's known (via your literature tools), surface open questions, and note
  prior art — but do not yet run a full hypothesis/experiment workflow; that
  comes later in the conversation.`;

/**
 * Build the system prompt: static preamble + a "Tools available to you:" section
 * generated by iterating the registry. Each line is the tool's registry key (the
 * name the model sees) and its description. This is the single source of truth —
 * never hardcode tool names in prose.
 */
function buildInstructions(): string {
  const toolLines = Object.entries(tools)
    .map(([name, tool]) => {
      const description =
        (tool as { description?: string }).description ??
        "(no description provided)";
      return `- ${name}: ${description}`;
    })
    .join("\n");

  return `${PREAMBLE}

Tools available to you:
${toolLines}`;
}

export const INSTRUCTIONS = buildInstructions();

/**
 * Anthropic prompt-caching breakpoint for the stable request prefix.
 *
 * WHY / MECHANISM (verified against the installed deps — do not "simplify" to a
 * top-level providerOptions.anthropic.cacheControl, which is a NON-standard
 * passthrough Anthropic ignores for prefix caching):
 *
 * Anthropic caches the request prefix in fixed order `tools → system → messages`
 * up to each `cache_control` breakpoint, reusing it across turns (cheaper +
 * faster) once the prefix exceeds the model minimum (~1024 tokens for Sonnet).
 *
 * The AI SDK (`ai@6`) only emits a per-block `cache_control` when the breakpoint
 * rides on a concrete block's `providerOptions`:
 *   - `@ai-sdk/anthropic@3` reads `providerOptions.anthropic.cacheControl` on the
 *     SYSTEM message (convertToAnthropicMessagesPrompt → system block) and on a
 *     TOOL definition (prepareTools → tool block).
 *   - A string `system` carries no providerOptions, so it can never be cached.
 *     Passing `system` as a `SystemModelMessage[]` lets the AI SDK forward
 *     `providerOptions` onto the system block (ai@6 index: system array map keeps
 *     `providerOptions`). This is the AI SDK's documented "pass a
 *     SystemModelMessage for caching" path.
 *
 * Because `system` sits AFTER `tools` in request order, ONE ephemeral breakpoint
 * on the system block caches the WHOLE `tools + system` prefix — exactly the
 * stable preamble re-sent every turn. We additionally mark the last tool (see
 * convex/tools/index.ts) so the tools block is cacheable even if the system
 * prompt is ever overridden away. Two breakpoints total — well under Anthropic's
 * 4-breakpoint limit, and orthogonal to any history breakpoint added per-call.
 */
export const CACHED_SYSTEM: SystemModelMessage[] = [
  {
    role: "system",
    content: INSTRUCTIONS,
    providerOptions: {
      anthropic: { cacheControl: { type: "ephemeral" } },
    },
  },
];

export const scientist = new Agent(components.agent, {
  name: "Convex Scientist",
  languageModel: anthropic(SCIENTIST_MODEL),
  instructions: INSTRUCTIONS,
  tools,
  // Cap the tool loop so a single generation can't run away.
  stopWhen: stepCountIs(MAX_STEPS),
});
